all: kactl-sa-implementation Repeats

.PHONY: all clean kactl-sa-implementation Repeats

clean:
	make -C kactl-sa-implementation/ clean
	make -C Repeats/ clean

kactl-sa-implementation:
	make -C kactl-sa-implementation/

Repeats:
	make -C Repeats/
