#include"util/util.h"
#include"TeraIndex/TeraIndex.h"
#include"TeraLCP/TeraLCP.h"

void printUsage() {
    std::cout << 
        "TeraIndex builds an index that enables computing matching statistics of a pattern.\n"
        "It requires as input the lcp index generated by TeraLCP. It adds LF and inverse phi to the lcp index.\n"
        "\n"
        "Usage: TeraIndex <arguments>\n"
        "Options:\n"
        "  Input:\n"
        "    -i          FILE                       REQUIRED       file name of input (ends with '" << lcp_index_extension << "'), an index generated by TeraLCP.\n"
        "    -o          FILE                       REQUIRED       base name of output file (index will be written to 'FILE" << ms_index_extension <<"'\n"
        "  Verification:\n"
        "    -vLF                                   optional       verify LF is a permutation with one cycle (takes O(n) time!)\n"
        "    -vPsi                                  optional       verify Psi is a permutation with one cycle(takes O(n) time!)\n"
        "    -vText                                 optional       verify text recoved by LF and Psi are equal (takes O(n) time and memory!!!)\n"
        "    -vPhi                                  optional       verify Phi is a permutation with one cycle (takes O(n) time!)\n"
        "    -vInvPhi                               optional       verify InvPhi is a permutation with one cycle (takes O(n) time!)\n"
        "  General:\n"
        "    -v          [quiet,time,verb]          optional       Verbosity, verb for most verbose output, time for timer info, and quiet for no output. time is default.\n"
        "    -h, --help                             optional       Print this help message.\n"
        ;
}

struct options{
    std::string inputFile, oindex = "";
    verbosity v = TIME;
    bool vLF = false, vPsi = false, vText = false, vPhi = false, vInvPhi = false;
}o;

void processOptions(const int argc, const char* argv[]) {
    std::vector<bool> used(argc);
    used[0] = true;

    if (argc == 1 || getArgument(argc, argv, used, "-h", false, false) != "" || getArgument(argc, argv, used, "--help", false, false) != "") {
        printUsage();
        exit(0);
    }

    o.inputFile = getArgument(argc, argv, used, "-i", true, true);
    o.oindex = getArgument(argc, argv, used, "-o", true, true) + ms_index_extension;
    std::string s = getArgument(argc, argv, used, "-v", false, true);
    if (s == "quiet")
        o.v = QUIET;
    else if (s == "time" || s == "")
        o.v = TIME;
    else if (s == "verb")
        o.v = VERB;
    else {
        std::cout << "Invalid value passed to -v '" << s << "'\n";
        exit(1);
    }
    o.vLF = getArgument(argc, argv, used, "-vLF", false, false) == "-vLF";
    o.vPsi = getArgument(argc, argv, used, "-vPsi", false, false) == "-vPsi";
    o.vText = getArgument(argc, argv, used, "-vText", false, false) == "-vText";
    o.vPhi = getArgument(argc, argv, used, "-vPhi", false, false) == "-vPhi";
    o.vInvPhi = getArgument(argc, argv, used, "-vInvPhi", false, false) == "-vInvPhi";
    for (int i = 0; i < argc; ++i)
        if (!used[i]) {
            std::cout << "Argument " << i << ", '" << argv[i] << "' not recognized or used as an argument for another option. It might have been passed more than once (invalid).\n";
            exit(1);
        }
    testInFile(o.inputFile);
    testOutFile(o.oindex);
}

int main(const int argc, const char*argv[]) {
    processOptions(argc, argv);
    if (o.v >= TIME) {
        std::string msg(argv[0]);
        for (int i = 1; i < argc; ++i)
            msg += std::string(" ") + argv[i];
        Timer.start(msg);
    }
    std::ifstream in(o.inputFile);
    std::ofstream out(o.oindex);
    if (!in.is_open()) {
        std::cerr << "Input file '" << o.inputFile << "' failed to open for reading!\n";
        exit(1);
    }
    if (!out.is_open()) {
        std::cerr << "Output file '" << o.oindex << "' failed to open for reading!\n";
        exit(1);
    }
    TeraIndex().constructFromLCPIndexFileWriteAndClear(in, out, o.v,  o.vLF, o.vPsi, o.vText, o.vPhi, o.vInvPhi);
    if (o.v >= TIME) { Timer.stop(); } //TeraIndex
}
