#include"util/util.h"
#include"matchingStatistics/msIndex.h"
#include"lcpComputer/lcpComputer.h"

static constexpr const char* ms_index_extension = ".ms_index";

void printUsage() {
    std::cout << 
        "msIndexBuilder builds an index that enables computing matching statistics of a pattern.\n"
        "It requires as input the lcp index generated by lcpCompter. It adds LF and inverse phi to the lcp index.\n"
        "\n"
        "Usage: msIndexBuilder <arguments>\n"
        "Options:\n"
        "  Input:\n"
        "    -i          FILE                       REQUIRED       file name of input (ends with '" << lcp_index_extension << "'), an index generated by lcpComputer.\n"
        "    -o          FILE                       REQUIRED       base name of output file (index will be written to 'FILE" << ms_index_extension <<"'\n"
        "    -v          [quiet,time,verb]          optional       Verbosity, verb for most verbose output, time for timer info, and quiet for no output. time is default.\n"
        "    -h, --help                             optional       Print this help message.\n"
        ;
}

struct options{
    std::string inputFile, oindex = "";
    verbosity v = TIME;
}o;

void processOptions(const int argc, const char* argv[]) {
    std::vector<bool> used(argc);

    if (argc == 1 || getArgument(argc, argv, used, "-h", false, false) != "" || getArgument(argc, argv, used, "--help", false, false) != "") {
        printUsage();
        exit(0);
    }

    o.inputFile = getArgument(argc, argv, used, "-i", true, true);
    o.oindex = getArgument(argc, argv, used, "-o", true, true);
    std::string s = getArgument(argc, argv, used, "-v", false, true);
    if (s == "quiet")
        o.v = QUIET;
    else if (s == "time" || s == "")
        o.v = TIME;
    else if (s == "verb")
        o.v = VERB;
    else {
        std::cout << "Invalid value passed to -v '" << s << "'\n";
        exit(1);
    }
    for (int i = 0; i < argc; ++i)
        if (!used[i]) {
            std::cout << "Argument " << i << ", '" << argv[i] << "' not recognized or used as an argument for another option. It might have been passed more than once (invalid).\n";
            exit(1);
        }
    testInFile(o.inputFile);
    testOutFile(o.oindex);
}

int main(const int argc, const char*argv[]) {
    processOptions(argc, argv);
}
